In [9]:
import os

import numpy as np
import pandas as pd

In [10]:
# new output dir
NEWS_DIR = "../data/raw/news"
PRICES_PATH = "../data/raw/prices.parquet"
OUT_DIR = "../data/processed"
os.makedirs(OUT_DIR, exist_ok=True)

In [11]:
TICKERS = ["AAPL", "JNJ"] #add more soon
news = pd.concat([pd.read_parquet(f"{NEWS_DIR}/{t}.parquet") for t in TICKERS], ignore_index=True)
news.head()

,ticker,created_at,headline,content,source,symbols
0,AAPL,2026-10-15 18:33:56+00:00,Anthropic Needs Nearly $2.7B in Additional Mon...,"<figure class=""wp-block-image size-large""><img...",benzinga,"[AAPL, AMZN, BTCUSD, GOOG, META, MSFT, NVDA, Q..."
1,AAPL,2026-10-15 18:04:31+00:00,Michael Burry's 'Red October' Warning: Why QQQ...,<p>Falling bond yields are failing to revive t...,benzinga,"[AAPL, AMZN, DIA, GOOGL, META, MSFT, NVDA, QQQ..."
2,AAPL,2026-10-15 17:26:44+00:00,"Meta Announces Release Of Muse Spark Open, The...",,benzinga,"[AAPL, META, MSFT]"
3,AAPL,2026-10-15 17:04:44+00:00,'Apple and Meta team up to make Muse AI model ...,,benzinga,"[AAPL, META, MSFT]"
4,AAPL,2026-10-15 16:47:46+00:00,Apple Hits $5 Trillion Market Cap as Nvidia's ...,"<p><strong>Apple Inc.</strong> <a href=""https:...",benzinga,"[AAPL, CRWV, NVDA, ORCL, TSM]"

In [5]:
prices = pd.read_parquet(PRICES_PATH)

# Data Cleaning

In [12]:
news.isna().sum()

ticker        0
created_at    0
headline      0
content       0
source        0
symbols       0
dtype: int64

In [19]:
empty = news["content"].fillna("").str.strip() == ""
print(empty.sum()/len(news))

0.2892123471838813

In [ ]:
news["text_for_sentiment"] = news["content"].where(~empty, news["headline"]) #use headline when content is empty

In [16]:
news.head()

,ticker,created_at,headline,content,source,symbols,text_for_sentiment
0,AAPL,2026-10-15 18:33:56+00:00,Anthropic Needs Nearly $2.7B in Additional Mon...,"<figure class=""wp-block-image size-large""><img...",benzinga,"[AAPL, AMZN, BTCUSD, GOOG, META, MSFT, NVDA, Q...","<figure class=""wp-block-image size-large""><img..."
1,AAPL,2026-10-15 18:04:31+00:00,Michael Burry's 'Red October' Warning: Why QQQ...,<p>Falling bond yields are failing to revive t...,benzinga,"[AAPL, AMZN, DIA, GOOGL, META, MSFT, NVDA, QQQ...",<p>Falling bond yields are failing to revive t...
2,AAPL,2026-10-15 17:26:44+00:00,"Meta Announces Release Of Muse Spark Open, The...",,benzinga,"[AAPL, META, MSFT]","Meta Announces Release Of Muse Spark Open, The..."
3,AAPL,2026-10-15 17:04:44+00:00,'Apple and Meta team up to make Muse AI model ...,,benzinga,"[AAPL, META, MSFT]",'Apple and Meta team up to make Muse AI model ...
4,AAPL,2026-10-15 16:47:46+00:00,Apple Hits $5 Trillion Market Cap as Nvidia's ...,"<p><strong>Apple Inc.</strong> <a href=""https:...",benzinga,"[AAPL, CRWV, NVDA, ORCL, TSM]","<p><strong>Apple Inc.</strong> <a href=""https:..."

In [18]:
prices.head()

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,AAPL,2020-01-02 05:00:00+00:00,71.28,72.33,71.03,72.27,146217352.0,283489.0,71.84
1,AAPL,2020-01-03 05:00:00+00:00,71.50,72.33,71.35,71.57,154711256.0,280441.0,71.91
2,AAPL,2020-01-06 05:00:00+00:00,70.69,72.18,70.44,72.14,125599968.0,242868.0,71.66
3,AAPL,2020-01-07 05:00:00+00:00,72.15,72.40,71.58,71.80,118227136.0,227871.0,71.96
4,AAPL,2020-01-08 05:00:00+00:00,71.50,73.26,71.50,72.95,142736804.0,261773.0,72.50